### ISSUE TITLE
ethX concept is broken with CentOS 7

### ISSUE THREAD

**Issue by jolexa** [dfederlein/vagrant-tower#8]
roles/common/tasks/main.yml references eth0 files which doesn't exist in CentOS 7. This breaks "vagrant up" out of the box.

**Comment by hisgarden** [comment]
I have the same issue, however I found a fix for that by replacing one line in roles/common/templates/ifcfg-eth0.j2:

replacing line 4: IPADDR={{ansible_eth1.ipv4.address}}
with this line:
IPADDR={{(ansible_eth1 | default(ansible_lo)).ipv4.address}}

the reason is ansible_eth1 may not be defined by default, 

This is based on one of the entry in URL below:
http://serverfault.com/questions/641326/issues-with-ansibles-default-error-handling-in-a-playbook
